language: node_js
node_js:
- 10
install:
- npm install -g codecov
script:
- yarn test
after_success:
- codecov
before_deploy:
- yarn build
deploy:
  provider: npm
  skip_cleanup: true
  edge: false
  email: aleksandryackovlev@yandex.ru
  api_key:
    secure: mXB11LnVR3MKOPlgnveeDo/jHF8AL2jHo5EMjYOq451FuxAoAZde3sy+WiFAKYMNiGqEDvWXqMIJtOJqfVrx5wUKjorP81806wsVQo8iyTVCeA8Uz7QFqv3R56iqSHyipPW5uCGDt7x+xk0KI/Dqg4fhfmYPih4EVVAMY6fn6foqYIesrCvNt/dVZwCkILRNejc9ZxlnpLQHPbtEhMKShn7hQOFvI7TdZ7XwGTzag7ncYmCFqYfJUemPdrCdkQkb7nrbehB0ivdRhMD7J/ypuh2nJvxotjV3p7hbU9Z2dI7P850Atv/8yexbgNMuDGZpZqH3L8Qn850cBRqqdNlwg1Io/bqfRJDxwTw18BYogPtMJ1VXA5jutXHYROrxK3jI6ogBtntnpDl2ZKd2WSLJbJYhRnnxk3VtrAT79wAi6oIlqFSGEoGffxXGBDS0gD4GSxs4YQ1FfrvXeezG8FObbMFgTa/e2IvtBU17ALP22InMaYD4npCZpHrzALyvHkMYhH6LBDyTwMKsMWxHPgX3MmZv561xE1YWfy7zhNmh1vCmzZ45H6Cdpy/72uqqz0JI6nZcHTUAPZVdBdnlmbvlQQbUv8xofgGulCkri+O/hMEmS9neFryLGwKMjZOTgeq71s6jiQIGsHUVCrAFqFrJdSp4WwepyoHIsp1xV+Gk/+4=
  on:
    tags: true
    repo: aleksandryackovlev/openapi-client-sdk-loader
