language: node_js
node_js:
- 10
install:
- npm install -g codecov
script:
- yarn test
after_success:
- codecov
before_deploy:
- yarn build
deploy:
  skip_cleanup: true
  provider: npm
  email: aleksandryackovlev@yandex.ru
  api_key:
    secure: E4ZUbovR7RkmAnnWX9fJrZ+JAhzozOem8PdUGlAdPWJ+/OCLY0v0cwlE5yF8l7nymYs6dBDrG2eC14s72vk+pAlvLx93wWZ6ZylgzrDsUcBvTDWT3jAlfolxeQYGpO+h8eI6gaFRMkfLGbK6VciVnzUZC6iLh4IVWbJqGzJ+wZ61d4LLpK0vnDnTTwUliJRkIlhmwkMPYyPq2cM/dyOFcWJzFltQ/UvMYkTr2pGZQzkWn0cYse1G7EdRFiSFyRdlnOxBI2f/jJKP8XC/hBAaD5xS0jgSjuK3nqO8tVpbHB/G4QXKlhK+AebLkHhEeYugHxbZeKCehHQZtHj5uO9YcZLpI/sA546YJdRyWFYQaWcMJJhbY3dvcMNmArCBmedVt+CLrPlRssnGJmHV99gNEWtP9IqIyl37bHFt/Fjt9ZZSNVur7ZRd++i5NMRbCz//9jLJralFVXbKuK3r2RS4hGNbUK0G9ecOK/yRsZjY1lB53khR4YSZt9av3+vGsrzWQwfguOlxfQLx72HydHVInjP4710gnGG3wc6Y8UmyIoFlwGFGqn+JK6rNd/j7HIfM7DOhdEhVpmV+s6FnfHfuoKNCoJcMp0b/u6rRzBUkQ19lenFnBr5zntJAF4++RsnR61SGt32KbZg95+lgHQ6EWcBiVjY0lkGSjCFWFkLCix4=
  on:
    tags: true
